categories = ["Added", "Changed", "Fixed", "Improved", "Removed"]
category_delimiters = ["[", "]"]
colored_output = true
enable_debug = true
enable_footers = false
excluded_commit_tags = []
show_commit_hash = false
show_prefix = false
sort_by = "date"
template_prefix = "JIRA-1234"
